from __future__ import annotations

COMMAND_VOLTAGE_LIMIT_V = 10.0
COMMAND_VOLTAGE_LIMIT_LABEL = "±10V"
COMMAND_VOLTAGE_NORMALIZATION_MODE = "peak_to_10V"
COMMAND_VOLTAGE_NORMALIZATION_OR_LIMIT_MODE = "peak_to_10V_or_limit"
